// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kUn2Pn1Bl7sl48TnitJsAoZz_vGFWPk',
    appId: '1:553106444206:web:86d29b94eb1e061fa7023f',
    messagingSenderId: '553106444206',
    projectId: 'achat-app-65856',
    authDomain: 'achat-app-65856.firebaseapp.com',
    storageBucket: 'achat-app-65856.appspot.com',
    measurementId: 'G-9THSQC3594',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4BUeRT9vQfMtbH1y4kmGfKRDGSSPr4BU',
    appId: '1:553106444206:android:0cfff458904807ffa7023f',
    messagingSenderId: '553106444206',
    projectId: 'achat-app-65856',
    storageBucket: 'achat-app-65856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8_KjYhiLs49hxE8dUGPFHz8MbOCBTOs',
    appId: '1:553106444206:ios:17de2b7b40e1bccba7023f',
    messagingSenderId: '553106444206',
    projectId: 'achat-app-65856',
    storageBucket: 'achat-app-65856.appspot.com',
    iosBundleId: 'com.example.achatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8_KjYhiLs49hxE8dUGPFHz8MbOCBTOs',
    appId: '1:553106444206:ios:8349668083921871a7023f',
    messagingSenderId: '553106444206',
    projectId: 'achat-app-65856',
    storageBucket: 'achat-app-65856.appspot.com',
    iosBundleId: 'com.example.achatApp.RunnerTests',
  );
}
